INTERLOK-678 Catch NoClassDefFoundError INTERLOK-678 #time 3h
If you include the log4j2-log4j bridge (which means you support code
that uses the Log4j API; then the Loader class does not exist so you
cannot do the Loader.getResource() even though isLog4jAvailable returns
true.

By adding the catch for the NoClassDef we can "upgrade" to log4j2 with
no other code changes by depending on
org.slf4j:slf4j-api:1.7.12
org.slf4j:jcl-over-slf4j:1.7.12
org.apache.logging.log4j:log4j-core:2.4.1
org.apache.logging.log4j:log4j-1.2-api:2.4.1
org.apache.logging.log4j:log4j-slf4j-impl:2.4.1
org.apache.logging.log4j:log4j-api:2.4.1

And excluding
ch.qos.logback:logback-classic
ch.qos.logback:logback-classic
org.slf4j:slf4j-log4j12
org.slf4j:jcl-over-slf4j
log4j:log4j
commons-logging

When building up the adapter-runtime.